{% set name = "fastimport" %}
{% set version = "0.9.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fastimport-{{ version }}.tar.gz
  sha256: 6ac99dda4e7b0b3ae831507b6d0094802e6dd95891feafde8cc5c405b6c149ca

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - fastimport
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jelmer/python-fastimport
  summary: VCS fastimport/fastexport parser
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  description: |
    This package provides a parser for and generator of the Git fastimport format.
  doc_url: https://www.kernel.org/pub/software/scm/git/docs/git-fast-import.html
  dev_url: https://github.com/jelmer/python-fastimport

extra:
  recipe-maintainers:
    - mikofski
    - xylar
